-- ====================================================================
-- SCHEMA SUPABASE: TABEL DUAS (DOA HARIAN & HADITS) + VECTOR EMBEDDINGS
-- Jalankan seluruh script ini di Supabase Dashboard -> SQL Editor -> Run
-- ====================================================================

-- 1. Pastikan ekstensi vector aktif
CREATE EXTENSION IF NOT EXISTS vector;

-- 2. Buat tabel duas
CREATE TABLE IF NOT EXISTS public.duas (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  dua_id INT NOT NULL UNIQUE,             -- ID unik dari API equran.id
  grup TEXT NOT NULL,                     -- Kategori (cth: "Doa Sehari-hari")
  nama TEXT NOT NULL,                     -- Nama/judul doa
  arabic_text TEXT NOT NULL,              -- Teks Arab berharakat
  transliteration TEXT,                   -- Transliterasi Latin
  translation TEXT NOT NULL,              -- Terjemahan Bahasa Indonesia
  tentang TEXT,                           -- Rujukan/Hadits (cth: "HR. Bukhari")
  tags TEXT[],                            -- Tags pencarian
  embedding VECTOR(1536),                 -- Vector embedding (1536 dimensi)
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Aktifkan Row Level Security (RLS)
ALTER TABLE public.duas ENABLE ROW LEVEL SECURITY;

-- Policy untuk read publik
DROP POLICY IF EXISTS "Allow public read access on duas" ON public.duas;
CREATE POLICY "Allow public read access on duas"
ON public.duas FOR SELECT
USING (true);

-- Policy untuk write (insert/update) melalui script seed
DROP POLICY IF EXISTS "Allow public write access on duas" ON public.duas;
CREATE POLICY "Allow public write access on duas"
ON public.duas FOR ALL
USING (true);

-- 4. Index HNSW untuk semantic vector similarity search berkecepatan tinggi
CREATE INDEX IF NOT EXISTS duas_embedding_hnsw_idx
ON public.duas
USING hnsw (embedding vector_cosine_ops);

-- 5. RPC Function: match_duas
-- Dipanggil oleh AI Assistant untuk mencari doa yang paling relevan dengan pertanyaan
CREATE OR REPLACE FUNCTION match_duas (
  query_embedding VECTOR(1536),
  match_threshold FLOAT DEFAULT 0.50,
  match_count INT DEFAULT 4
)
RETURNS TABLE (
  id BIGINT,
  dua_id INT,
  grup TEXT,
  nama TEXT,
  arabic_text TEXT,
  transliteration TEXT,
  translation TEXT,
  tentang TEXT,
  similarity FLOAT
)
LANGUAGE plpgsql
AS $$
BEGIN
  RETURN QUERY
  SELECT
    duas.id,
    duas.dua_id,
    duas.grup,
    duas.nama,
    duas.arabic_text,
    duas.transliteration,
    duas.translation,
    duas.tentang,
    1 - (duas.embedding <=> query_embedding) AS similarity
  FROM public.duas
  WHERE 1 - (duas.embedding <=> query_embedding) > match_threshold
  ORDER BY similarity DESC
  LIMIT match_count;
END;
$$;
